sudo: required
env:
  global:
  - secure: ID+8X4vKsFAhbVsJQ3mdZFqgntocDOEAPEVcZ7wjh+HzX96JZo25dx0XFDu1+QDNVDupn/nrDg+1aAeUh09wdqZg1Po83aH0OqZpFKSt7weY54D3u81HduJUlM2qkGh/RorexsmHW7DYLVfnpu1DsZ/Xs21CvWEDIjQ/uYsYI850++j+vNYsMbEj42Hju92dQJd30LmPXFsF79ex7gOraogQ3/PltYDLKDacQ6VOXIGDBMEMOoBC8MRlZuk+xRfLwvwjyiYCoHsLkGQQlGNI5Zy6n1ZyxX88Pyq0oUVa72CM+5frTq+Gpp/WsSxVJWduTXnmcUjIAvcCn0sMmDwGKRpILOOaAqKZuLJe4Vjqyk7xfMEd904OGJeC8HoRjoL60CGj1rjJxQSuLOKpFN/VZ3wdkyzyur8V3DnmxLMUoEs4AM7n1maJGE71t8B8hXK1/EMA1HYhqJnrAKIvBh5UZtRZgGb6j57yyZDBPN+dP1f2gTRpYXMzZAarC/ZvaJrVrE2e8ZT0yxZ84P9QZEv8WFtQb0L/G7xjxkb9SwxEvBjTTetXoNjmZ/emZpErCcR0emqHZUJWF8RB9aUbXgJNYXFkkCYRJmOn+/GxRFoSLGlhq+MzmKMrw6FTk+6vtNUdguV9MRItfvixP43BmRfxODteuee9i1j95BwXO2Ur4ew=
  - secure: dOiAeeg4GTckbdQ0r1+o3TCBCx8xQm20A+EoNZuPLp0ieYOCGlqgM9SrOI1pXLBMMFaEXaSCW10SuyzBU6ij8uQzQiOE1KN6xftixIuSP8n8TDI75Z19XWhX1OwVrX6LDxP1ROFtPQPXTrWQ4WbX8y5fO3/mnEpRkRFEXNblLv1/PbIUUsTvpQfuYbrbdViYFVzSdyI8+1QsPrjJcH8WCOURI8Vki8Auh+yUvpkbOys0n41juOB21OHxDLhzbXP+Z9sjEiR4ZKMFvfceZzOgCKAT1AqOCJQVXQFHr7YxR593pun1EQINzKvy4IyPXNi4XibldSI45ZjOT3jprHpfTsvXf543A+GbQj1PJ6GVKku0F2TAa92piCpkKVQEitJL/10aOiB8zEHx7CJpnn31JkPF6sXK1ixcNAaa6zunlcH8gePX/nj7dI97Cdt8+SliEoW1zEYgV+jnhM2JsfLrskGwVJknoymjRjPOyjxUgMn0lqfby2eIGt2WXI+y2YjCcSLRPXmEOcxG5fJuoxGE6kXGe3dcO4BD5AHAQutXReDCO0oMXxK0qcokjuQYLXE5xfXeD3pRDc11EN99oi+j0wrlWLz5NFuPWqgxqi90Mk5yP9TwjsM6AejkY69S5d0xlHEpnHAv+jsg9w+j8OgE4YMCbAjK7BKi7E0vZm+qudE=
  - secure: CVKG5YYosDlXzWVQ3zzAyPJTVxcj9bNHbFBr+402ai6h5WcaQPVwxbHF1v0roccZd38mtAw/3Pin7di1QWUOaKmIaPK2fQxvRceX6Lv6fWlOyXDY9331UrwR+QcX2GDLeVb0E+8mIhRlDwJS2LOFta5FuGsTvnf7prja4IEueDpWjXUDRdkj39WIMzDr5EekQz+Rd90WfNmVNfW9dVZE5ObGQNrzbCbbNGsbO8Be9qNQbGyHwlt0IF4JqaCAk0ILLLpitqlDDZ36LXTS7WEGe4+TEBpSPqB/72tU9WMvSYqtv8zYwRQxsgTDrrPv2f18d+q6AVFCfSHsKnVyCqspNM/4RSxAit9U9tAR9Izj9ivX64eBFoYYMD5noTCNlT0zuzIaYzxrdXlGgtIjKBW5278aXSq0Aa4jYRElPgTLLK9C9RpGXbXRQB7rFCw3Xdy2s/NktVff3/SoCBaE3U8xbGT4YAb7gxIyfoGusd6MVmeRz6v7kZ/BsIWdw8qhqrvPic2BXRjhK7xe9mkXk5X9/6yv9429v3lhEZslEyrwqU4t34z275cyCKxPa48T6tB3zf010AEWQqCz8AGjsfrD3VY9f45pgPrSbdSGCbK672xCK9fWTP/Em8QMjpUfKgQK3QoNRHO0tQFuCL/8uCRdJHtYJlbAf1e+G78eqhIc7dY=
  - secure: kGuHQBg0nzn8hGNpD4BFXtB1ngAkLbW/PTTRD1N/9VAx85P+A+dRG3/xW1kKmjckjOaEgKUHDmqzcW+Cye6METPdbaJHZS+GLPkdy+JlHfxImk5Whj0EI3xhRvjuhQbh4No6JwJnfVLuFbOPLkURBYdZkkocTzgti1SO1PzF/XGyjbPIjr/x5vMqTNikoZG7QeRunLbJvb61B8V82Oedwr5FvhD8o2sC6CYdrMNADMdXr7dLKO2rsfW0twRAlGMvVvK1n3u5OVzI7jYBd6pzYEJRU3Nps2g0+iMpjGi5uYH7xdPTtvKfww47XR4b4buWXY4VbW8rZKsx8BEpVkbgkkNrJVdQOK5apYXuYwsmfjUn7VbG+WJDAX3CCTYqzuw2Ep4erynFy6zFi5SsERfM9ybtMFAAAlfChUumpTLwK/zJJ+nsuZe1FULId8IGpg4m8/OB1J2pEe+AtPKwZxG2A1yejWSW60WrEvQn7bAYXr7zTl/a5eQiAHrnhlKS9lJ/RS0uS98f8lA1+AFVR8+XNiSxAkPBTBTbr3Z3hgYKETFkBBJEU0Eoegt2/YOVVqKTvMuGGtAJ5Q4t8CIaOzprpYkYyjHXe+oNWyjZBcbumUvJxaSHhMqLcOEkvcIetTsnR+3ddVh60OzhCftKGFrJm5ZzqoiiRBdOV1XM+2GakAo=
  - REPO=level-three-rest
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64

language: go
go:
- 1.7

services:
- docker

before_script:
- export TZ=Pacific/Auckland
- export "PATH=/home/travis/gopath/bin:$PATH"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

branches:
  only:
  - master

before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cover
- go get github.com/Masterminds/glide

script:
- glide install
- go build
- go test -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
- docker build -t level-three-rest -t $REPO:$TRAVIS_BUILD_NUMBER -f Dockerfile .

after_success:
- pip install --user awscli
- export PATH=$PATH:/$HOME/.local/bin
- aws ecr create-repository --repository-name $REPO --region us-west-2
- eval $(aws ecr get-login --region us-west-2)
- docker tag $REPO:$TAG $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TAG
- docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TAG
